Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,6 +8,14 @@ on:
         required: true
         default: false
         type: boolean
+      android_version:
+        required: true
+        type: string
+        default: android12
+      kernel_version:
+        required: true
+        type: string
+        default: 5.10
       FILE:
         type: string
         description: "Configuration file"
@@ -449,17 +457,32 @@ jobs:
           git add -A
           git commit -m "Custom suffix & removed -dirty"
 
-      - name: Add ${{ matrix.ksu }}
+      # - name: Add ${{ matrix.ksu }}
+      #   run: |
+      #     cd kernel_workspace
+      #     if [ "${{ matrix.ksu }}" == "KernelSU" ]; then
+      #       curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v1.0.5
+      #     elif [ "${{ matrix.ksu }}" == "KernelSU-Next" ]; then
+      #       curl -LSs "https://raw.githubusercontent.com/hemasai1109/Custom_kernel_OnePlus_Nord3/refs/heads/main/.github/workflows/ksun.sh" | bash -s next-susfs-a13-5.15-dev
+      #     elif [ "${{ matrix.ksu }}" == "SukiSU-Ultra" ]; then
+      #       curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
+      #     fi
+      - name: Add KernelSU Next
+        shell: bash
         run: |
-          cd kernel_workspace
-          if [ "${{ matrix.ksu }}" == "KernelSU" ]; then
-            curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v1.0.5
-          elif [ "${{ matrix.ksu }}" == "KernelSU-Next" ]; then
-            curl -LSs "https://raw.githubusercontent.com/hemasai1109/Custom_kernel_OnePlus_Nord3/refs/heads/main/.github/workflows/ksun.sh" | bash -s next-susfs-a13-5.15-dev
-          elif [ "${{ matrix.ksu }}" == "SukiSU-Ultra" ]; then
-            curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
-          fi
-
+          echo "Changing to configuration directory: $CONFIG..."
+          cd "kernel_workspace/kernel-5.10"
+          
+          echo "Adding KernelSU..."
+          curl -LSs "https://raw.githubusercontent.com/hemasai1109/Custom_kernel_OnePlus_Nord3/refs/heads/main/.github/workflows/ksun.sh" | bash -s next
+          
+          git submodule update --init --recursive
+          cd KernelSU-Next/kernel
+          KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
+          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+          sed -i "s/DKSU_VERSION=11998/DKSU_VERSION=${KSU_VERSION}/" Makefile
+          
+          git submodule update --init --recursive
       - name: Checkout SUSFS
         run: |
           cd kernel_workspace/kernel-5.10
@@ -474,14 +497,125 @@ jobs:
         run: |
           cd kernel_workspace/kernel-5.10
           
-          cp susfs4ksu/kernel_patches/fs/* fs
-          cp susfs4ksu/kernel_patches/include/linux/* include/linux
-          patch -p1 < susfs4ksu/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch
+          # cp susfs4ksu/kernel_patches/fs/* fs
+          # cp susfs4ksu/kernel_patches/include/linux/* include/linux
+          # patch -p1 < susfs4ksu/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch
 
-          if [ "${{ matrix.ksu }}" == "KernelSU" ]; then
-            cd KernelSU
-            patch -p1 < ../../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch
+          echo "Applying SUSFS patches..."
+          
+          # Copy SUSFS patches
+          cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch ./
+          cp susfs4ksu/kernel_patches/fs/* ./common/fs/
+          cp susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
+
+          # if [ "${{ matrix.ksu }}" == "KernelSU" ]; then
+          #   cd KernelSU
+          #   patch -p1 < ../../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch
+          # fi
+          echo "Kernel_Workspace/kernel-5.10 Under things 👍"
+          ls
+          cd KernelSU-Next
+          echo "KernelSU-Next under things 👍"
+          ls
+          
+          echo "Applying next SUSFS patches..."
+          susfs_version=$(grep '#define SUSFS_VERSION' ../include/linux/susfs.h | awk -F'"' '{print $2}')
+          echo "SUSVER=$susfs_version" >> $GITHUB_ENV
+          BASE_VERSION=10200
+          cd ./kernel
+          KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" $BASE_VERSION)
+          sed -i "s/DKSU_VERSION=11998/DKSU_VERSION=${KSU_VERSION}/" Makefile
+          cd ..
+          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+          echo "KernelSU Next Version: $KSU_VERSION"
+          echo "SusFS Version: $susfs_version"
+          
+          case "$susfs_version" in
+            "v1.5.5"|"v1.5.6"|"v1.5.7")
+              cp "../../kernel_patches/next/0001-kernel-implement-susfs-v1.5.5-v1.5.7-KSUN-v1.0.8.patch" "./ksun_susfs_latest.patch"
+              ;;
+            "v1.5.8")
+              cp ../../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./
+              patch -p1 --forward --fuzz=3 < 10_enable_susfs_for_ksu.patch  || true
+              cp "../../kernel_patches/next/susfs_fix_patches/$susfs_version/fix_apk_sign.c.patch" ./
+              patch -p1 --forward --fuzz=3 < fix_apk_sign.c.patch
+              cp "../../kernel_patches/next/susfs_fix_patches/$susfs_version/fix_core_hook.c.patch" ./
+              patch -p1 --forward --fuzz=3 < fix_core_hook.c.patch
+              cp "../../kernel_patches/next/susfs_fix_patches/$susfs_version/fix_selinux.c.patch" ./
+              patch -p1 --forward --fuzz=3 < fix_selinux.c.patch
+              cp "../../kernel_patches/next/susfs_fix_patches/$susfs_version/fix_ksud.c.patch" ./
+              patch -p1 --forward --fuzz=3 < fix_ksud.c.patch
+              ;;
+            "v1.5.9")
+              cp ../../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./
+              patch -p1 --forward < 10_enable_susfs_for_ksu.patch  || true
+              
+              for file in $(find ./kernel -maxdepth 2 -name "*.rej" -printf "%f\n" | cut -d'.' -f1); do
+                  echo "Patching file: $file.c with fix_$file.c.patch"
+                  patch -p1 --forward < "../../kernel_patches/next/susfs_fix_patches/$susfs_version/fix_$file.c.patch"
+              done
+              
+              # Fix build errors (no rejects; Still giving errors)
+              patch -p1 --forward < "../../kernel_patches/next/susfs_fix_patches/$susfs_version/fix_kernel_compat.c.patch"
+              ;;
+            *)
+              echo "Invalid version: $susfs_version"
+              exit 1
+              ;;
+          esac
+          patch -p1 --forward < ksun_susfs_latest.patch || true
+          
+          
+          # Change to common directory and apply SUSFS patch
+          cd ../
+          
+          if [ "${{ inputs.android_version }}" = "android15" ] && [ "${{ inputs.kernel_version }}" = "6.6" ]; then
+              if ! grep -qxF '#include <trace/hooks/fs.h>' ./fs/namespace.c; then
+                  sed -i '/#include <trace\/hooks\/blk.h>/a #include <trace\/hooks\/fs.h>' ./fs/namespace.c
+              else
+                  echo "Line already present. Skipping insert."
+              fi
           fi
+          patch -p1 < 50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch || true
+          
+          KERNEL_VERSION="${{ inputs.kernel_version }}"
+          MIN_VERSION="5.16"
+          
+          if [ "$(printf '%s\n' "$KERNEL_VERSION" "$MIN_VERSION" | sort -V | head -n1)" = "$KERNEL_VERSION" ]; then
+            echo "Patching ptrace!"
+            patch -p1 -F 3 < "../../kernel_patches/gki_ptrace.patch"
+          else
+            echo "Kernel >= $MIN_VERSION, skipping ptrace patch"
+          fi
+          
+          if [ "${{ inputs.model }}" == "OPAce5Pro" ] || [ "${{ inputs.model }}" == "OP13" ]; then
+            echo "Patching hmbird!"
+            echo 'obj-y += hmbird_patch.o' >> ./drivers/Makefile
+            patch -p1 -F 3 < "../../../kernel_patches/oneplus/hmbird/hmbird_kernel_patch.patch"
+            echo "Patching hmbird files!"
+            cd ./kernel/sched
+            rm -rf ext.c ext.h build_policy.c slim.h slim_sysctl.c
+            patch -p1 -F 3 < "../../../../../kernel_patches/oneplus/hmbird/hmbird_files_patch.patch"
+          else
+            echo "Not OPAce5Pro / OP13 , skipping fengchi patch"
+          fi
+      - name: Apply KSUN Hooks
+        shell: bash
+        run: |
+          echo "Changing to configuration directory: $CONFIG..."
+          cd "kernel_workspace/kernel_platform/"
+          echo "Applying KSUN Hooks..."
+          cp ../../kernel_patches/next/scope_min_manual_hooks_v1.4.patch ./manual_hooks.patch
+          patch -p1 < ./manual_hooks.patch
+          
+      - name: Apply Hide Stuff Patches
+        shell: bash
+        run: |
+          echo "Changing to configuration directory: $CONFIG..."
+          cd "kernel_workspace/kernel_platform"
+          # Apply additional patch
+          cp ../../kernel_patches/69_hide_stuff.patch ./
+          patch -p1 -F 3 < 69_hide_stuff.patch
 
       - name: Add Configuration
         run: |
